name: Sync / Async

on:
  workflow_dispatch:

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Run Async tests
        run: time node async.js
      - name: Cleanup
        run: node cleanup.js
      - name: Run Sync tests
        run: time node sync.js
      - name: Cleanup
        run: node cleanup.js
      - name: Run optimal tests
        run: node optimal.js
      - name: Cleanup
        run: node cleanup.js

  
  
